return {
	"Drank construction coffee",
	"xponen was here", -- seriously, it's like 8 years since the guy played.
	"Didn't find love here",
	"voi vittu",
	"Encountered a funny looking A",
	"Went the way of Commander Junior",
	"Phailure is the path to n00bdom.",
	"Uses Attack instead of Fight",
	"Fucked in sky",
	"Protip: Read the newbie guide",
	"Forgot to plop a brain.",
	"Why you self d?",
	"No comment",
	"Encountered an OP <attackerunit>",
	"Ran out of coffee, sauna, and beer.",
	"Prkl",
	"Forgot to take their shoes off",
	"Went where the socks disappear to",
	"Forgot to water their cactus",
	"Protip: To kill enemy units, shoot at them until they die.",
	"Please remember to recycle!",
	"Forgot their aa",
	"Forgot Poland",
	"Made too many Slings",
	"Not enough commorph!",
	"Less threatening than the love boat",
	"Protip: You can counter <attackerunit> with more <attackerunit>",
	"Protip: Morph dgun next time!",
	"Protip: you can escape falling units by not being under them",
}
